### ISSUE TITLE
Unable to build in zig 0.15.2

### ISSUE THREAD

**Issue by Boilingtub** [Snektron/vulkan-zig#212]
There seems to be an issue with the xml_path parameter. 

```
~/.cache/zig/p/vulkan-0.0.0-r7Ytx91DAwDKIXS2K_fFa-c_SJ5py7K1eCKwPcc33NcQ/src/main.zig:105:39: error: expected type 'mem.Allocator', found '[]const u8'
    const xml_src = cwd.readFileAlloc(xml_path, allocator, .unlimited) catch |err| {
                                      ^~~~~~~~
/home/hendrik/.local/bin/zig-x86_64-linux-0.15.2/lib/std/mem/Allocator.zig:1:1: note: struct declared here
//! The standard memory allocation interface.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hendrik/.local/bin/zig-x86_64-linux-0.15.2/lib/std/fs/Dir.zig:1985:47: note: parameter type declared here
pub fn readFileAlloc(self: Dir, allocator: mem.Allocator, file_path: []const u8, max_bytes: usize) ![]u8 {
```

It looks as if the function parameters xml_path and allocator were swapped, specifying the type of std.mem.Allocator to xml_path, and the type []const u8 to allocator.

It is a improper solution, but it compiles when changing lines 105 and 110 in the main.zig file to 
```
    const xml_src = cwd.readFileAlloc(allocator, xml_path, 5000000) catch |err| {
        std.process.fatal("failed to open input file '{s}' ({s})", .{ xml_path, @errorName(err) });
    };

    const maybe_video_xml_src = if (maybe_video_xml_path) |video_xml_path|
        cwd.readFileAlloc(allocator, video_xml_path, 5000000) catch |err| {
            std.process.fatal("failed to open input file '{s}' ({s})", .{ video_xml_path, @errorName(err) });
```
simply swapping the allocator and xml_path parmeters and replacing .unlimited with a very large number

**Comment by Boilingtub** [comment]
I see, thank you. 
Using the 0.15-compat branch completely fixes the issue.
My mistake, I will make sure to use the correct branch in the future !

**Comment by chrischtel** [comment]
Fixed it for me also. But why not pushing this to master?
