### ISSUE TITLE
Doesn't compile on 0.15.0-dev.1380+e98aeeb73

### ISSUE THREAD

**Issue by Kierteiyu** [Snektron/vulkan-zig#199]
When I attempt to compile a project with vulkan-zig, I get this error
```
/src/xml.zig:442:49: error: struct 'array_list.ArrayListAligned(xml.Attribute,null)' has no member named 'empty'
array_list.zig:31:12: note: struct declared here
    return struct {

**Comment by Kierteiyu** [comment]
I am so dumb. You have to get a newer version for this to work.
