### ISSUE TITLE
Compile error `root source file struct 'fs.File' has no member named 'stdout'`

### ISSUE THREAD

**Issue by MakeItEnd** [Snektron/vulkan-zig#194]
When trying to compile the latest commit with zig 0.14.1 I get:

```sh
/home/alexhex/.cache/zig/p/vulkan-0.0.0-r7Ytx5w-AwB0hzckD1mPHma0VgtiJ2DHj5dvgzWVwk2e/src/main.zig:46:32: error: root source file struct 'fs.File' has no member named 'stdout'
            var w = std.fs.File.stdout().writer(&buf);
                    ~~~~~~~~~~~^~~~~~~
/home/alexhex/projects/zig-x86_64-linux-0.14.1/lib/std/fs/File.zig:1:1: note: struct declared here
/// The OS-specific file descriptor or file handle.
```

I think it's from this commit `0fd576a7e5d67ff31400793f965d1d0f10cf94d2`

Was this library was updated to no longer work with zig 0.14?

If so this field `.minimum_zig_version = "0.14.0-dev.1359+e9a00ba7f",` in `build.zig.zon` should be updated to reflect this.

**Comment by Snektron** [comment]
https://github.com/Snektron/vulkan-zig/tree/zig-0.14-compat
